"""empty message

Revision ID: 69738fb15c4a
Revises: 
Create Date: 2019-12-19 18:36:59.161517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69738fb15c4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client', ['client_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    # ### end Alembic commands ###
