"""empty message

Revision ID: c1288f922351
Revises: 
Create Date: 2019-12-20 09:44:38.371308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1288f922351'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'client_secret',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.drop_index('client_key', table_name='client')
    op.drop_column('client', 'updated_at')
    op.drop_column('client', 'created_at')
    op.drop_column('client', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('client', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('client', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.create_index('client_key', 'client', ['client_key'], unique=True)
    op.alter_column('client', 'client_secret',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
