"""empty message

Revision ID: e6764180e402
Revises: 
Create Date: 2020-01-04 23:46:10.933626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6764180e402'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('metode_pembayaran', sa.String(length=255), nullable=True))
    op.alter_column('transaction', 'biaya_ongkir_total',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('transaction', 'harga_barang_total',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('transaction', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('transaction', 'total_barang',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('transaction', 'total_harga',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'total_harga',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('transaction', 'total_barang',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('transaction', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('transaction', 'harga_barang_total',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('transaction', 'biaya_ongkir_total',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('transaction', 'metode_pembayaran')
    # ### end Alembic commands ###
